image: maven:latest
#inspired by https://gitlab.com/gitlab-examples/maven/simple-maven-example
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode"

cache:
  paths:
    - .m2/repository/
    - target/

Build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile


TimesTest:
  stage: test
  script:
      - mvn -Dtest=tokenReader.TimesTest test

IpTest:
  stage: test
  script:
    - mvn -Dtest=tokenReader.IpTest test

G6Test:
  stage: test
  script:
    - mvn -Dtest=G6.G6Test test

ExpritTest:
  stage: test
  script:
    - mvn -Dtest=exprit.ExpritTest test

ExprTest:
  stage: test
  script:
    - mvn -Dtest=expr.ExprTest test

ParseTreeVisitorTest:
  stage: test
  script:
    - mvn -Dtest=calculators.parseTreeVisitor.parseTreeVisitorTest test

GrammarActionsTest:
  stage: test
  script:
    - mvn -Dtest=calculators.grammarActions.GrammarActionsTest test

pTListener:
  stage: test
  script:
    - mvn -Dtest=calculators.pTListener.PTListenerTest test
#In2OutRunnable:
#  stage: test
#  script:
#    - mvn -Dtest=echo.runnable.Input2OutputTest test

#EchoActor:
#  stage: test
#  script:
#    - mvn -Dtest=echo.actor.EchoActorTest test

#In2OutActor:
#  stage: test
#  script:
#    - mvn -Dtest=echo.actor.Input2OutputTest test

#DistEchoActor:
#    stage: test
#    script:
#      - mvn -Dtest=echo.actor.DistEchoActorTest test

#-Greeter:
 # stage: test
 # script:
  # - mvn -Dtest=greeter.actor.GreeterTest test
#ChatRoom:
 # stage: test
  #script:
   # - mvn -Dtest=chat.actor.ChatRoomTest test

#UniNetcat:
#  stage: test
#  script:
#    - mvn -Dtest=netcat.uni.tcp.NetcatTest test

#BidiNetcat:
#    stage: test
#    script:
#      - mvn -Dtest=netcat.bidi.tcp.NetcatTest test



deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."